import { test, expect, type Page } from './fixtures'
import { PDFDocument, StandardFonts, degrees } from 'pdf-lib'
import { readFile, writeFile } from 'node:fs/promises'

async function source(path: string, count = 3) {
  const pdf = await PDFDocument.create()
  const font = await pdf.embedFont(StandardFonts.Helvetica)
  for (let i = 0; i < count; i++) {
    const page = pdf.addPage([612, 792])
    page.drawText(`RELIABILITY PAGE ${i + 1}`, { x: 70, y: 680, size: 24, font })
  }
  await writeFile(path, await pdf.save())
}
async function open(page: Page, path: string) {
  await page.goto('/')
  await page.locator('input[type=file]').first().setInputFiles(path)
  await expect(page.locator('.pdf-page canvas').first()).toBeVisible()
}
async function exported(page: Page, path: string) {
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export PDF', exact: true }).click()
  await (await download).saveAs(path)
  return PDFDocument.load(await readFile(path))
}

test('library duplicate, rename, favorite, reopen and delete operate on real saved documents', async ({ page }, info) => {
  const path = info.outputPath('library.pdf')
  await source(path)
  await open(page, path)
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page.locator('.stage-top-hint')).toContainText('Saved to local library')
  await page.getByTitle('Close document').click()
  await page.getByRole('button', { name: 'Documents', exact: true }).click()
  await page.getByLabel('More actions for library.pdf', { exact: true }).click()
  await page.locator('.forge-row-menu').getByRole('button', { name: 'Duplicate', exact: true }).click()
  await expect(page.locator('.forge-archive-item')).toHaveCount(2)
  await page.getByLabel('More actions for library copy.pdf', { exact: true }).click()
  await page.locator('.forge-row-menu').getByRole('button', { name: 'Rename', exact: true }).click()
  const renameDialog = page.getByRole('dialog', { name: 'Rename document' })
  await renameDialog.getByLabel('Document name').fill('renamed.pdf')
  await renameDialog.getByRole('button', { name: 'Save Name' }).click()
  const row = page.locator('.forge-archive-item').filter({ hasText: 'renamed.pdf' })
  await row.getByLabel('Add to favorites', { exact: true }).click()
  await page.getByRole('button', { name: 'Starred', exact: true }).click()
  await expect(page.locator('.forge-archive-item')).toHaveCount(1)
  await row.locator('.forge-archive-open').click()
  await expect(page.getByLabel('Document name')).toHaveValue('renamed.pdf')
  expect((await exported(page, info.outputPath('copy-export.pdf'))).getPageCount()).toBe(3)
  await page.getByTitle('Close document').click()
  await page.getByRole('button', { name: 'Documents', exact: true }).click()
  await page.getByRole('button', { name: 'All', exact: true }).click()
  await page.getByLabel('More actions for renamed.pdf', { exact: true }).click()
  await page.locator('.forge-row-menu').getByRole('button', { name: 'Remove from archive' }).click()
  const removeDialog = page.getByRole('dialog', { name: 'Remove this document?' })
  await expect(removeDialog).toContainText('The original file on your computer will not be changed.')
  await removeDialog.getByRole('button', { name: 'Remove Document' }).click()
  await expect(page.locator('.forge-archive-item')).toHaveCount(1)
  await expect(page.locator('.forge-archive-item')).toContainText('library.pdf')
  await page.reload()
  await page.getByRole('button', { name: 'Documents', exact: true }).click()
  await expect(page.locator('.forge-archive-item')).toHaveCount(1)
})

test('bulk rotate, extract, delete and undo preserve real pages and rotations', async ({ page }, info) => {
  const path = info.outputPath('bulk.pdf')
  await source(path)
  await open(page, path)
  await page.getByLabel('Select page 1', { exact: true }).check()
  await page.getByLabel('Select page 3', { exact: true }).check()
  await page.getByTitle('Rotate selected right').click()
  const download = page.waitForEvent('download')
  await page.getByTitle('Extract selected pages').click()
  const extractPath = info.outputPath('selected.pdf')
  await (await download).saveAs(extractPath)
  const extracted = await PDFDocument.load(await readFile(extractPath))
  expect(extracted.getPageCount()).toBe(2)
  expect(extracted.getPages().map(p => p.getRotation().angle)).toEqual([90, 90])
  await page.getByTitle('Delete selected pages').click()
  await expect(page.locator('.stage-top-hint')).toContainText('Selected pages deleted')
  expect((await exported(page, info.outputPath('deleted.pdf'))).getPageCount()).toBe(1)
  await page.getByTitle('Undo', { exact: true }).click()
  const restored = await exported(page, info.outputPath('undo.pdf'))
  expect(restored.getPages().map(p => p.getRotation().angle)).toEqual([90, 0, 90])
  await page.getByTitle('Redo', { exact: true }).click()
  expect((await exported(page, info.outputPath('redo.pdf'))).getPageCount()).toBe(1)
  await page.getByLabel('Select page 1', { exact: true }).check()
  await page.getByTitle('Delete selected pages').click()
  await expect(page.locator('.stage-top-hint')).toContainText('at least one page')
  expect((await exported(page, info.outputPath('retained.pdf'))).getPageCount()).toBe(1)
})

test('viewer modes, fit, fullscreen and boundary navigation remain usable', async ({ page }, info) => {
  const path = info.outputPath('viewer.pdf')
  await source(path)
  await open(page, path)
  await page.getByTitle('Continuous view', { exact: true }).click()
  await expect(page.locator('.continuous-stack .page-view')).toHaveCount(3)
  await expect(page.locator('.continuous-stack .pdf-page canvas').first()).toBeVisible()
  await page.getByTitle('Two-page view', { exact: true }).click()
  await expect(page.locator('.pdf-page')).toHaveCount(2)
  await page.getByTitle('Single page view', { exact: true }).click()
  await expect(page.locator('.pdf-page')).toHaveCount(1)
  await page.getByTitle('Fit width', { exact: true }).click()
  await page.getByTitle('Fit page', { exact: true }).click()
  await page.getByTitle('Fullscreen', { exact: true }).click()
  await expect.poll(() => page.evaluate(() => Boolean(document.fullscreenElement))).toBe(true)
  await page.getByTitle('Fullscreen', { exact: true }).click()
  await expect.poll(() => page.evaluate(() => Boolean(document.fullscreenElement))).toBe(false)
  await page.locator('.floating-nav input').fill('999')
  await expect(page.locator('.floating-nav input')).toHaveValue('3')
  await expect(page.getByRole('button', { name: 'Next page', exact: true })).toBeDisabled()
  await page.locator('.floating-nav input').fill('0')
  await expect(page.locator('.floating-nav input')).toHaveValue('1')
  await expect(page.getByRole('button', { name: 'Previous page', exact: true })).toBeDisabled()
  await page.keyboard.press('Control+k')
  await page.getByPlaceholder('Name the task…').fill('Add text')
  await page.locator('.product-command-results').getByRole('button', { name: /Add text/ }).click()
  await expect(page.getByTitle('Add text', { exact: true })).toHaveClass(/active/)
})

test('existing page rotations render and export without flattening document structure', async ({ page }, info) => {
  const pdf = await PDFDocument.create()
  const sheet = pdf.addPage([612, 792])
  sheet.setRotation(degrees(90))
  const form = pdf.getForm().createTextField('rotated_field')
  form.setText('kept'); form.addToPage(sheet, { x: 40, y: 60, width: 120, height: 24 })
  const path = info.outputPath('pre-rotated.pdf')
  await writeFile(path, await pdf.save())
  await open(page, path)
  const canvas = await page.locator('.pdf-page canvas').first().boundingBox()
  expect(canvas!.width).toBeGreaterThan(canvas!.height)
  const reopened = await exported(page, info.outputPath('pre-rotated-export.pdf'))
  expect(reopened.getPage(0).getRotation().angle).toBe(90)
  expect(reopened.getForm().getTextField('rotated_field').getText()).toBe('kept')
})

test('all fillable field types, clear values and rotation persist without losing AcroForms', async ({ page }, info) => {
  const pdf = await PDFDocument.create()
  const sheet = pdf.addPage([612, 792])
  const form = pdf.getForm()
  const text = form.createTextField('text')
  text.setText('Original'); text.addToPage(sheet, { x: 50, y: 680 })
  form.createCheckBox('check').addToPage(sheet, { x: 50, y: 620 })
  const dropdown = form.createDropdown('dropdown')
  dropdown.addOptions(['A', 'B']); dropdown.select('A'); dropdown.addToPage(sheet, { x: 50, y: 560 })
  const list = form.createOptionList('list')
  list.addOptions(['One', 'Two', 'Three']); list.enableMultiselect(); list.select(['One', 'Two']); list.addToPage(sheet, { x: 50, y: 420 })
  const radio = form.createRadioGroup('radio')
  radio.addOptionToPage('Yes', sheet, { x: 300, y: 620 }); radio.addOptionToPage('No', sheet, { x: 350, y: 620 }); radio.select('Yes')
  const locked = form.createTextField('locked')
  locked.setText('Read only'); locked.addToPage(sheet, { x: 50, y: 350 }); locked.enableReadOnly()
  const path = info.outputPath('all-fields.pdf')
  await writeFile(path, await pdf.save())
  await open(page, path)
  await page.getByTitle('Form fields', { exact: true }).click()
  const field = (name: string) => page.locator('.form-field').filter({ has: page.locator('span', { hasText: new RegExp(`^${name}$`) }) })
  await expect(field('locked').locator('input')).toBeDisabled()
  await expect(field('list').locator('select')).toHaveValues(['One', 'Two'])
  await field('text').locator('input').fill('Persisted value')
  await field('text').locator('input').press('Tab')
  await expect(page.locator('.stage-top-hint')).toContainText('Form field updated')
  await field('check').locator('input').check()
  await expect(field('check').locator('input')).toBeChecked()
  await field('list').locator('select').selectOption(['Two', 'Three'])
  await expect(field('list').locator('select')).toHaveValues(['Two', 'Three'])
  await field('dropdown').locator('select').selectOption('')
  await expect(field('dropdown').locator('select')).toHaveValue('')
  await field('radio').locator('select').selectOption('')
  await expect(field('radio').locator('select')).toHaveValue('')
  await page.getByTitle('Pages', { exact: true }).click()
  await page.getByTitle('Rotate right', { exact: true }).click()
  const reopened = await exported(page, info.outputPath('all-fields-export.pdf'))
  expect(reopened.getPage(0).getRotation().angle).toBe(90)
  const saved = reopened.getForm()
  expect(saved.getFields()).toHaveLength(6)
  expect(saved.getTextField('text').getText()).toBe('Persisted value')
  expect(saved.getCheckBox('check').isChecked()).toBe(true)
  expect(saved.getDropdown('dropdown').getSelected()).toEqual([])
  expect(saved.getOptionList('list').getSelected()).toEqual(['Two', 'Three'])
  expect(saved.getRadioGroup('radio').getSelected()).toBeUndefined()
  expect(saved.getTextField('locked').getText()).toBe('Read only')
})